[theme]
primaryColor = "#7792E3"
backgroundColor = "#273346"
secondaryBackgroundColor = "#B9F1C0"
textColor = "#FFFFFF"
font = "sans serif"

[server]
port = 8501
enableCORS = false
maxUploadSize = 50

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
